baresip: Add dependency on glib-2.0-native
This is needed to build "ctrl_dbus" module where
"baresipbus.c" gets generated with "gdbus-codegen".

Otherwise compilation fails with:
--------------------->8-----------------
./gen.sh: line 2: gdbus-codegen: command not found
...
cc1: fatal error: modules/ctrl_dbus/baresipbus.c: No such file or directory
compilation terminated.
...
make: *** [mk/mod.mk:49: build-x86_64/modules/ctrl_dbus/baresipbus.o] Error 1
make: *** Waiting for unfinished jobs....
modules/ctrl_dbus/ctrl_dbus.c:69:10: fatal error: baresipbus.h: No such file or directory
   69 | #include "baresipbus.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
--------------------->8-----------------

Signed-off-by: Alexey Brodkin <alexey.brodkin@gmail.com>